#!/usr/bin/env python3
"""Proud Points seed: the old Microsoft Forms submissions -> SQL.

Source: SharePoint eAppsHub, Shared Documents/School Proud Points for
Website.xlsx (sheet Submissions), read through the Microsoft 365 connector.
The connector stops xlsx reads at row 264 of 313, so the 2026-10-08 seed
holds rows 1-264. Sean exported the full sheet as CSV on 2026-10-09; rows 265
onward were loaded from it with --min-id 265 --no-ideas.

Usage:
  python3 -I scripts/proud-points-seed.py DUMP DIRECTORY.json > out.sql
    DUMP            the sheet saved as .csv, or a connector read of the
                    workbook (tab-separated rows)
    DIRECTORY.json  [[loc_no, school_name, school_level], ...] from
                    bcps_school_directory where not is_archived

Writes inserts for bcps_proud_point_legacy (every point, school matched to a
location number) and bcps_proud_point_ideas (an anonymized, themed sample for
the Ideas gallery). No submitter names or emails leave the sheet.
"""
import argparse
import json
import re
import sys
from datetime import datetime

ap = argparse.ArgumentParser()
ap.add_argument('dump')
ap.add_argument('directory')
ap.add_argument('--min-id', type=int, default=1)
ap.add_argument('--no-ideas', action='store_true')
args = ap.parse_args()

rows = []
if args.dump.lower().endswith('.csv'):
    # The sheet saved as CSV from Excel: Windows-1252, not UTF-8.
    import csv
    raw = open(args.dump, 'rb').read()
    try:
        text = raw.decode('utf-8-sig')
    except UnicodeDecodeError:
        text = raw.decode('cp1252')
    for c in list(csv.reader(text.splitlines(True)))[1:]:
        if c and c[0].strip().isdigit() and int(c[0]) >= args.min_id:
            rows.append((c + [''] * 18)[:18])
else:
    for line in open(args.dump, encoding='utf-8').read().split('\n'):
        if not re.match(r'^\d+\t\d+/', line):
            continue
        c = line.split('\t') + [''] * 18
        if int(c[0]) >= args.min_id:
            rows.append(c[:18])

directory = json.load(open(args.directory))
by_loc = {d[0]: d for d in directory}

# Names the matcher cannot reach on its own: renamed or K-8 conversions.
ALIASES = {
    'Sheridan Technical High': '1051',
    'Atlantic Technical High School': '2221',
    'Hollywood Central Elementary': '0121',
    'Seagull Alternative High School': '0601',
    'William T. McFatter Technical High': '1291',
    'Coral Cove Elementary': '2011',
    'Silver Shores Elementary School': '3581',
    'Coconut Creek Elementary': '1421',
    'Broward Estates Elementary': '0501',
}
LEVEL_WORDS = {'elementary': 'Elementary', 'middle': 'Middle', 'high': 'High', 'center': 'Center'}
STOP = {'school', 'the', 'of', 'and', 'jr', 'dr', 'k', '8', 'pk', 'prek'}


def toks(s):
    return [t for t in re.findall(r'[a-z0-9]+', s.lower().replace('&', 'and')) if t not in STOP]


def match(name):
    if name in ALIASES:
        return by_loc[ALIASES[name]]
    nt = toks(name)
    ns = set(nt)
    lvl = next((LEVEL_WORDS[t] for t in nt if t in LEVEL_WORDS), None)
    best = None
    for loc, dn, dl in directory:
        dt = [t for t in toks(dn) if t not in LEVEL_WORDS]
        if dt and all(t in ns for t in dt):
            score = len(dt) * 10 + (5 if lvl == dl else (-20 if lvl and lvl != dl and dl in LEVEL_WORDS.values() else 0))
            if best is None or score > best[0]:
                best = (score, [loc, dn, dl])
    return best[1] if best and best[0] > 0 else None


def q(v):
    return 'null' if v is None else "'" + str(v).replace("'", "''") + "'"


def ts(s):
    for fmt in ('%m/%d/%Y %H:%M', '%m/%d/%y %H:%M'):
        try:
            return datetime.strptime(s.strip(), fmt).strftime('%Y-%m-%d %H:%M:00-04')
        except ValueError:
            pass
    return None


def day(s):
    for fmt in ('%m/%d/%Y', '%m/%d/%y'):
        try:
            return datetime.strptime(s.strip(), fmt).strftime('%Y-%m-%d')
        except ValueError:
            pass
    return None


out = []
unmatched = set()
legacy = []
for c in rows:
    name = c[5].strip()
    m = match(name)
    if not m:
        unmatched.add(name)
    for slot, text in enumerate(c[6:12] + [c[14]], 1):
        t = text.strip()
        if t:
            legacy.append((int(c[0]), name, m[0] if m else None, slot, t, ts(c[2]), day(c[16])))

out.append('-- Generated by scripts/proud-points-seed.py; source rows %d-%d (%d rows).' % (
    rows[0][0] and int(rows[0][0]), int(rows[-1][0]), len(rows)))
if unmatched:
    out.append('-- No directory match: ' + ', '.join(sorted(unmatched)))
for i in range(0, len(legacy), 200):
    out.append('insert into public.bcps_proud_point_legacy (source_row, school_name, school_location_nbr, slot, text, submitted_at, date_posted) values')
    out.append(',\n'.join('(%d, %s, %s, %d, %s, %s, %s)' % (r[0], q(r[1]), q(r[2]), r[3], q(r[4]), q(r[5]), q(r[6])) for r in legacy[i:i + 200]) + '\non conflict (source_row, slot) do nothing;')

if not args.no_ideas:
    THEMES = [
        ('Academic achievement', r'\b(a|b)[- ]?rated|"?[ab]"? school|grade|score|proficien|\bfast\b|test|gains?|graduat|honor roll|achievement|percent|%'),
        ('Arts and music', r'\bband|music|chorus|choir|orchestra|\bart\b|\barts\b|theat|drama|dance|visual'),
        ('STEM and technology', r'stem|steam|robot|coding|computer|engineer|science|math|technology|drone|vex|1:1|device'),
        ('Athletics', r'athlet|sport|football|basketball|soccer|track|volleyball|baseball|softball|swim|championship|state champ'),
        ('Signature programs', r'magnet|\bib\b|international baccalaureate|aice|cambridge|advanced placement|\bap\b|dual enrollment|academy|career|cte|certification|program'),
        ('Clubs and student life', r'club|student council|activit|leadership|safety patrol|news crew|yearbook|debate'),
        ('Community and family', r'communit|partner|famil|parent|pta|volunteer|service'),
        ('Awards and recognition', r'award|recogni|ranked|nationally|state[- ]wide|top \d|#1|blue ribbon|five star|5[- ]star|school of excellence'),
        ('Culture and climate', r'safe|culture|inclusive|kindness|nurtur|character|positive|attendance|social|emotional|mental'),
    ]
    LEVEL_LABEL = {'Elementary': 'Elementary', 'Middle': 'Middle', 'High': 'High'}
    GENERIC = set('school elementary middle high center academy k-8 the of and at community charter magnet prep learning technical college'.split())
    # Anything that names a person, gives the web team an instruction, or is a
    # dated notice is not an idea another school can borrow.
    BAD = re.compile(r'(tryout|^keep:|\(to go|\d{1,2}:\d\d)|\b(mr|mrs|ms|dr|principal|congratulat|please|link|click|website|here|contact|call|email|www|http|teacher of the year)\b', re.I)
    PERSON = re.compile(r'^[A-Z][a-z]+ [A-Z][a-z]+\.?$')
    # Anonymized by school level means no idea may carry a word that points
    # at one school: any distinctive word from any school name in the
    # directory (mascots often share it, e.g. Eagle), or a Broward city.
    COMMON = set('school elementary middle high center academy the of and at community park lakes lake creek beach hills city springs heights palm trail village arts north south west east central magnet museum stem steam virtual early learning college education excellence schools young country technical preparatory collegiate resource montessori primary alternative'.split())
    CITIES = ['hallandale', 'lauderhill', 'pembroke', 'pompano', 'hollywood', 'davie', 'plantation', 'sunrise', 'tamarac', 'margate', 'miramar', 'weston', 'parkland', 'dania', 'oakland', 'wilton', 'deerfield', 'coconut', 'coral', 'cooper', 'lauderdale']
    NAMED = sorted({w.lower() for _, dn, _ in directory for w in re.findall(r'[A-Za-z]+', dn) if len(w) > 3 and w.lower() not in COMMON} | set(CITIES))
    IDENTIFYING = re.compile(r'\b(' + '|'.join(NAMED) + r')\b', re.I)
    # A replacement that left the sentence broken ("A our school", "our your").
    GARBLED = re.compile(r"\b(a|the|our|of) our school|our school [A-Z]\.|our school s\b|our school ,|our school \.|our your|this week|will compete|knights|chief|charged up|\bon (january|february|march|april|may|june|july|august|september|october|november|december)\b", re.I)

    def theme(t):
        tl = t.lower()
        return next((n for n, rx in THEMES if re.search(rx, tl)), None)

    cands, seen = [], set()
    for c in rows:
        name = c[5].strip()
        m = match(name)
        level = LEVEL_LABEL.get(m[2], 'Center or other') if m else 'Center or other'
        words = [w for w in re.findall(r"[A-Za-z']+", name) if w.lower() not in GENERIC and len(w) > 2]
        if m:
            words += [w for w in re.findall(r"[A-Za-z']+", m[1]) if w.lower() not in GENERIC and len(w) > 2]
        acr = ''.join(w[0] for w in re.findall(r'[A-Za-z]+', name)).upper()
        for p in c[6:12]:
            t = re.sub(r'^\s*\d+\.\s*', '', p.strip())
            for w in set(words):
                t = re.sub(r"\b" + re.escape(w) + r"('s)?\b", '[School]', t, flags=re.I)
            if len(acr) >= 3:
                t = re.sub(r'\b' + re.escape(acr) + r'\b', '[School]', t)
            t = re.sub(r"(\[School\]\s*)+(Elementary|Middle|High|K-8)?\s*(School)?('s)?", lambda mm: 'our school' + ("'s" if mm.group(4) else '') + ' ', t)
            t = re.sub(r'\s+', ' ', t).strip(' •-–')
            if not t:
                continue
            t = t[0].upper() + t[1:]
            th = theme(t)
            key = re.sub(r'[^a-z0-9]', '', t.lower())
            if not th or not (40 <= len(t) <= 200) or BAD.search(t) or PERSON.match(t) or IDENTIFYING.search(t) or GARBLED.search(t) or '[' in t or key in seen:
                continue
            seen.add(key)
            cands.append((th, level, t, bool(re.search(r'\d', t))))
    # Number-led ideas first (the new form leads with a data point), at most
    # six per theme and level so no one school type crowds the gallery.
    cands.sort(key=lambda x: (not x[3], len(x[2])))
    count, ideas = {}, []
    for th, level, t, _ in cands:
        k = (th, level)
        if count.get(k, 0) >= 6:
            continue
        count[k] = count.get(k, 0) + 1
        ideas.append((th, level, t))
    out.append('insert into public.bcps_proud_point_ideas (theme, school_level, text, sort) values')
    out.append(',\n'.join('(%s, %s, %s, %d)' % (q(a), q(b), q(t), i) for i, (a, b, t) in enumerate(ideas)) + '\non conflict (text) do nothing;')

sys.stdout.write('\n'.join(out) + '\n')
print('legacy points %d, rows %d, unmatched %d' % (len(legacy), len(rows), len(unmatched)), file=sys.stderr)
